## Model 1: AR(1)+Noise

```{r}
library(astsa)
set.seed(12345)

### Model: AR(1)+Noise
phi=0.9
W<-0.1
V<-1
n=200

x<-ts(arima.sim(n,model=list(ar=phi),sd=sqrt(W)))
y<-ts(x+rnorm(n,mean=0,sd=sqrt(V)))
sim1<-data.frame(x,y)

plot(sim1$y,main=paste("Phi:",phi," V:",V,"  W:",W),type="l")
lines(sim1$x,col="red",lwd=2)

```



### Filter ith the correct parameters

```{r}
data<- matrix(sim1$y)
A<- 1
Phi<-phi
cQ<-sqrt(W)
cR<-sqrt(V)
Sigma0<-1000
mu0<-0
sim1.kf<-Kfilter(data,A,mu0,Sigma0,Phi,cQ,cR)

```


```{r}
fil.mu<-ts(c(sim1.kf$Xf))
plot(sim1$y,type="p",main="Filter")
lines(sim1$x,lwd=2,col=2)
lines(fil.mu,col=1,lwd=2)
```



```{r}

likelihood2<-function(param){
	Phi<-matrix(param[1])
	cQ<-chol(matrix(param[2]))

	temp<-Kfilter(data,A,mu0,Sigma0,Phi,cQ,cR)
	temp$like
	}
```

```{r}

likelihood2(c(0.8,0.5))
likelihood2(c(0.7,0.2))
likelihood2(c(0.6,0.1))
```


```{r}
#versemblan?a condicionada a W=0.2
like<-rep(0,20)
for (i in 1:20){
	phi<-i/20
	like[i]<--likelihood2(c(phi,0.2))
	}
plot((1:20)/20,like,type="l",main="logLik(phi,W=0.2)",xlab="phi")
abline(v=0.9,lty=2)
```

### Maximum Likelihood Estimation

```{r}

maxim<-optim(c(1,1),likelihood2,lower=c(-0.9999,0.001),upper=c(0.999,Inf),method="L-BFGS-B")
maxim
```

```{r}

	param<-maxim$par
	lphi<-sort(c(1:10)*2*param[1]/10)
	lw<-sort(c(1:10)*2*param[2]/10)
	grid<-expand.grid(lphi,lw)
	like<-rep(0,dim(grid)[1])
	for (i in 1:dim(grid)[1]){
		like[i]<-likelihood2(unlist(grid[i,]))
	}
	like<-matrix(like,10,10)
 	contour(lphi,lw,nlevels=35,like,xlab="Phi",ylab="W")
	abline(v=param[1],lty=3)
	abline(h=param[2],lty=3)
	text(param[1],param[2],round(like[5,5],2),cex=0.8)


```

```{r}
data<- matrix(sim1$y)
A<- 1
Phi<-maxim$par[1]
cQ<-sqrt(maxim$par[2])
cR<-sqrt(V)
Sigma0<-1000
mu0<-0
sim1.kf2<-Kfilter(data,A,mu0,Sigma0,Phi,cQ,cR)

```

```{r}
fil.mu<-ts(c(sim1.kf2$Xf))
plot(sim1$y,type="p",main="Filter")
lines(sim1$x,lwd=2)
lines(fil.mu,col=2,lwd=2)
```